/*! ****************************************************************************
 * Spine v0.0.0-alpha.0
 *
 * Spine ....
 * (you can download it from npm or github repositories)
 * Copyright (c) 2021 Mobilabs <contact@mobilabs.fr> (http://www.mobilabs.fr).
 * Released under the MIT license. You may obtain a copy of the License
 * at: http://www.opensource.org/licenses/mit-license.php).
 * Built from ES6Kadoo v1.0.7.
 * ************************************************************************** */
/*! Generated by Kadoo v1.0.3 */
const $__ES6GLOB={};!function(t,e){"use strict";"function"==typeof define&&define.amd?define([""],e):"object"==typeof exports?module.exports=e(t):t.Spine=e(t)}($__ES6GLOB,t=>{"use strict";let e={src:{spine:{},util:{util:{}}},extend:function(t,e){for(var n=Object.keys(e),i=0;i<n.length;i++)t[n[i]]=e[n[i]]}};return function(){const n=e.src.util.util,i=t.Spine,r={_library:{name:"Spine",version:"0.0.0-alpha.0"},_setTestMode:()=>[],noConflict(){return t.Spine=i,this},whoami(){return this._library},getString:()=>n.getString(),getArray:()=>n.getArray(),NAME:"Spine",VERSION:"0.0.0-alpha.0"};e.src.spine=r}(),function(){const t={getString:()=>"I am a string!",getArray:()=>[1,2,3]};e.extend(e.src.util.util,t)}(),e.src.spine});export default $__ES6GLOB.Spine;